---
title: "Complaints_Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

#Set up and load libraries.

library(flexdashboard)
library(tidyverse) 
library(janitor) 
library(readxl) 
library(scales)
library(lubridate)
library(ggthemes)
library(ggplot2)
library(esquisse)
library(dplyr)

complaints <- readRDS("complaints.rds") %>%
  clean_names()

complaints %>%
  count(company, sort = TRUE)


#----------------------------------------------

#Begin data analysis and ggplot charting:

# 1) Sort by company.

complaints %>%
  count(company, sort = TRUE)

top_companies <- complaints %>% 
  filter(company %in% c("EQUIFAX", "INC.", 
                        "TRANSUNION INTERMEDIATE HOLDINGS, INC.", 
                        "Experian Information Solutions Inc.", 
                        "BANK OF AMERICA, NATIONAL ASSOCIATION", 
                        "WELLS FARGO & COMPANY", 
                        "JPMORGAN CHASE & CO.", 
                        "CITIBANK, N.A.")) %>% 
  arrange(desc(company))

ggplot(top_companies, aes(company)) +
  geom_bar(color = "#9ebcda", fill = "#9ebcda") +
  coord_flip() +
  scale_y_continuous(name = "Number of Complaints", labels = scales::comma) +
  scale_x_discrete(name = "Company Name") +
  labs(title = "Companies With Most Complaints", 
       subtitle = "Financial Protection Bureau 2022",
       caption = "Source: Consumer Complaint Database") +
  scale_x_discrete(labels=c("Wells Fargo", "Transunion", "J.P. Morgan", "Experian", "Citibank", "Bank of America")) +
  theme_fivethirtyeight()


# 2) Sort for complaints by type. 

top_method <- ggplot(complaints, aes(submitted_via))
top_method + geom_bar(color = "#9ebcda", fill = "#9ebcda") +
  coord_flip() +
  scale_y_continuous(name = "Frequency", labels = scales::comma) +
  scale_x_discrete(name = "Method of Contact") +
  labs(title = "Number of Complaints by Method", 
       subtitle = "Financial Protection Bureau 2022",
       caption = "Source: Consumer Complaint Database") +
  theme_fivethirtyeight()

# 3) Sort by state.

complaints %>%
  count(state, sort = TRUE)

top_states <- complaints %>% 
  filter(state %in% c("CA", 
                      "FL", 
                      "TX", 
                      "NY", 
                      "GA", 
                      "PA", 
                      "IL", 
                      "NJ",
                      "NC",
                      "OH")) %>% 
  arrange(desc(company))

ggplot(top_states, aes(state)) +
  geom_bar(color = "#9ebcda", fill = "#9ebcda") +
  scale_y_continuous(name = "Number of Complaints", labels = scales::comma) +
  scale_x_discrete(name = "State") +
  labs(title = "States With Most Complaints", 
       subtitle = "Financial Protection Bureau 2022",
       caption = "Source: Consumer Complaint Database") +
  theme_fivethirtyeight()

#Now start pasting into flexdashboard chart chunks and testing html knitting:

```

Column {data-width=650}
-----------------------------------------------------------------------

### The below chart shows the data sorted by company to see which financial institutions recieved the most customer complaints. 

```{r, echo = FALSE}

ggplot(top_companies, aes(company)) +
  geom_bar(color = "#9ebcda", fill = "#9ebcda") +
  coord_flip() +
  scale_y_continuous(name = "Number of Complaints", labels = scales::comma) +
  scale_x_discrete(name = "Company Name") +
  labs(title = "Companies With Most Complaints", 
       subtitle = "Financial Protection Bureau 2022",
       caption = "Source: Consumer Complaint Database") +
  scale_x_discrete(labels=c("Wells Fargo", "Transunion", "J.P. Morgan", "Experian", "Citibank", "Bank of America")) +
  theme_fivethirtyeight()

```

Column {data-width=350}
-----------------------------------------------------------------------

### This chart shows how most of the complaints were filed. 

```{r, echo = FALSE}

top_method <- ggplot(complaints, aes(submitted_via))
top_method + geom_bar(color = "#9ebcda", fill = "#9ebcda") +
  coord_flip() +
  scale_y_continuous(name = "Frequency", labels = scales::comma) +
  scale_x_discrete(name = "Method of Contact") +
  labs(title = "Number of Complaints by Method", 
       subtitle = "Financial Protection Bureau 2022",
       caption = "Source: Consumer Complaint Database") +
  theme_fivethirtyeight()

```

### Here, the data is sorted by state to see in which states the complaints were filed most frequently. 

```{r, echo = FALSE}

ggplot(top_states, aes(state)) +
  geom_bar(color = "#9ebcda", fill = "#9ebcda") +
  scale_y_continuous(name = "Number of Complaints", labels = scales::comma) +
  scale_x_discrete(name = "State") +
  labs(title = "States With Most Complaints", 
       subtitle = "Financial Protection Bureau 2022",
       caption = "Source: Consumer Complaint Database") +
  theme_fivethirtyeight()

```

